export const ZOOTTELKEEPER_INDEX_LIST_BEGINNING_TEXT='%% Zoottelkeeper: Beginning of the autogenerated index file list %%'
export const ZOOTTELKEEPER_INDEX_LIST_END_TEXT='%% Zoottelkeeper: End of the autogenerated index file list %%'
